--Criando WH's
CREATE OR REPLACE WAREHOUSE XSMALL_WH WITH 
   WAREHOUSE_SIZE = 'XSMALL' 
   WAREHOUSE_TYPE = 'STANDARD' 
   AUTO_SUSPEND = 60 
   AUTO_RESUME = TRUE 
   MIN_CLUSTER_COUNT = 1 
   MAX_CLUSTER_COUNT = 1 
   SCALING_POLICY = 'STANDARD';
   
CREATE OR REPLACE WAREHOUSE SMALL_WH WITH 
   WAREHOUSE_SIZE = 'SMALL' 
   WAREHOUSE_TYPE = 'STANDARD' 
   AUTO_SUSPEND = 60 
   AUTO_RESUME = TRUE 
   MIN_CLUSTER_COUNT = 1 
   MAX_CLUSTER_COUNT = 1 
   SCALING_POLICY = 'STANDARD';

CREATE OR REPLACE WAREHOUSE MEDIUM_WH WITH 
   WAREHOUSE_SIZE = 'MEDIUM' 
   WAREHOUSE_TYPE = 'STANDARD' 
   AUTO_SUSPEND = 60 
   AUTO_RESUME = TRUE 
   MIN_CLUSTER_COUNT = 1 
   MAX_CLUSTER_COUNT = 1 
   SCALING_POLICY = 'STANDARD';

CREATE OR REPLACE WAREHOUSE LARGE_WH WITH 
   WAREHOUSE_SIZE = 'LARGE' 
   WAREHOUSE_TYPE = 'STANDARD' 
   AUTO_SUSPEND = 60 
   AUTO_RESUME = TRUE 
   MIN_CLUSTER_COUNT = 1 
   MAX_CLUSTER_COUNT = 1 
   SCALING_POLICY = 'STANDARD';
   
CREATE OR REPLACE WAREHOUSE XLARGE_WH WITH 
   WAREHOUSE_SIZE = 'XLARGE' 
   WAREHOUSE_TYPE = 'STANDARD' 
   AUTO_SUSPEND = 60 
   AUTO_RESUME = TRUE 
   MIN_CLUSTER_COUNT = 1 
   MAX_CLUSTER_COUNT = 1 
   SCALING_POLICY = 'STANDARD';