CREATE OR REPLACE DATABASE DW_SALES1;
CREATE OR REPLACE SCHEMA SALES1;

USE DATABASE DW_SALES1;
USE SCHEMA SALES1;
USE WAREHOUSE XSMALL_WH;

-- Cria as tabelas de Sales, Customer, Item, Nation e Region para as quais serão aplicadas as policies
-- Tabela Sales
CREATE OR REPLACE TABLE SALES1 (
  O_ORDERKEY NUMBER(38,0)
  ,O_CUSTKEY NUMBER(38,0)
  ,O_TOTALPRICE NUMBER(12,2)
  ,O_ORDERDATE DATE
);

-- Tabela Itens
CREATE OR REPLACE TABLE ITEM1(
  L_ORDERKEY NUMBER(38,0)
  ,L_PARTKEY NUMBER(38,0)
  ,L_SUPPKEY NUMBER(38,0)
  ,L_LINENUMBER NUMBER(38,0)
  ,L_QUANTITY NUMBER(12,2)
  ,L_EXTENDEDPRICE NUMBER(12,2)
  ,L_DISCOUNT NUMBER(12,2)
  ,L_TAX NUMBER(12,2)
);

-- Tabela Customer
CREATE OR REPLACE TABLE CUSTOMER1 (
  C_CUSTKEY NUMBER(38,0)
  ,C_NAME VARCHAR(25)
  ,C_NATIONKEY NUMBER(38)
  ,C_MKTSEGMENT VARCHAR(10)
);

-- Tabela Nation
CREATE OR REPLACE TABLE NATION1 (
  N_NATIONKEY NUMBER(38)
  ,N_NAME VARCHAR(25)
  ,N_REGIONKEY NUMBER(38,0)
);

-- Tabela Region
CREATE OR REPLACE TABLE REGION1 (
  R_REGIONKEY NUMBER(38,0)
  ,R_NAME VARCHAR(25)
);

--Tabela Part (Product)
CREATE OR REPLACE TABLE PART1 (
P_PARTKEY	NUMBER(38,0)
,P_NAME	VARCHAR(55)
,P_MFGR	VARCHAR(25)
,P_BRAND	VARCHAR(10)
,P_TYPE	VARCHAR(25)
,P_SIZE	NUMBER(38,0)
,P_CONTAINER	VARCHAR(10)
,P_RETAILPRICE	NUMBER(12,2)
,P_COMMENT	VARCHAR(23)
);

-- Tabela Supplier
CREATE OR REPLACE TABLE SUPPLIER1 (
S_SUPPKEY	NUMBER(38,0)
,S_NAME	VARCHAR(25)
,S_ADDRESS	VARCHAR(40)
,S_NATIONKEY	NUMBER(38,0)
,S_PHONE	VARCHAR(15)
,S_ACCTBAL	NUMBER(12,2)
,S_COMMENT	VARCHAR(101)
);

-- Uso um Warehouse maior para as cargas
USE WAREHOUSE XLARGE_WH;

--Insert data nas tabelas criadas, partindo da database SNOWFLAKE_SAMPLE_DATA
INSERT INTO SALES1 (
  O_ORDERKEY
  ,O_CUSTKEY
  ,O_TOTALPRICE
  ,O_ORDERDATE
)
SELECT
  O_ORDERKEY
  ,O_CUSTKEY
  ,O_TOTALPRICE
  ,O_ORDERDATE
FROM
  SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS;


INSERT INTO ITEM1 (
  L_ORDERKEY
  ,L_PARTKEY
  ,L_SUPPKEY
  ,L_LINENUMBER
  ,L_QUANTITY
  ,L_EXTENDEDPRICE
  ,L_DISCOUNT
  ,L_TAX
)
SELECT
  L_ORDERKEY
  ,L_PARTKEY
  ,L_SUPPKEY
  ,L_LINENUMBER
  ,L_QUANTITY
  ,L_EXTENDEDPRICE
  ,L_DISCOUNT
  ,L_TAX
FROM
  SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM;


INSERT INTO CUSTOMER1 (
  C_CUSTKEY
  ,C_NAME
  ,C_NATIONKEY
  ,C_MKTSEGMENT
)
SELECT
  C_CUSTKEY
  ,C_NAME
  ,C_NATIONKEY
  ,C_MKTSEGMENT
FROM
  SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER;
  
INSERT INTO NATION1 (
  N_NATIONKEY
  ,N_NAME
  ,N_REGIONKEY
)
SELECT
  N_NATIONKEY
  ,N_NAME
  ,N_REGIONKEY
FROM
  SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION;
  
INSERT INTO REGION1 (
  R_REGIONKEY 
  ,R_NAME
)
SELECT
  R_REGIONKEY 
  ,R_NAME
FROM
  SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.REGION; 
  
  
INSERT INTO PART1
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PART;

INSERT INTO SUPPLIER1
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.SUPPLIER;
  

--Diminuo o Warehouse
USE WAREHOUSE XSMALL_WH;