-- Imporante setar o contexto da role responsável
USE ROLE SYSADMIN;
USE DATABASE DW_SALES1;
USE SCHEMA SALES1;
USE WAREHOUSE XSMALL_WH;

--Criando a fato Sales
CREATE OR REPLACE TABLE DW_SALES1.SALES1.FACT_SALES1
(
ORDERKEY NUMBER(38,0)
,CUSTKEY NUMBER(38,0)
,PARTKEY NUMBER(38,0)
,SUPPKEY NUMBER(38,0)
,PARTSUPPKEY NUMBER(38,0)
,NATIONKEY NUMBER(38,0)
,REGIONKEY NUMBER(38,0)
,ORDERDATE DATE
,ORDERYEAR STRING
,ORDERMONTH NUMERIC(12,0)
,ORDERMONTHNAME STRING
,ORDERQUARTER STRING
,TOTALPRICE NUMBER(12,2)
,LINENUMBER NUMBER(38,0)
,QUANTITY NUMBER(38,0)
,EXTENDEDPRICE NUMBER(12,2) 
,DISCOUNT NUMBER(12,3)
,TAX NUMBER(12,3)
,DISCOUNTVALUE NUMBER(12,2)
,NETPRICE NUMBER(12,2)
,TAXVALUE NUMBER(12,2)
,SALEPRICE NUMBER(12,2)
);

USE WAREHOUSE XLARGE_WH;

INSERT INTO DW_SALES1.SALES1.FACT_SALES1
SELECT
    L_ORDERKEY AS ORDERKEY
    ,O_CUSTKEY AS CUSTKEY
    ,L_PARTKEY AS PARTKEY
    ,L_SUPPKEY AS SUPPKEY
    ,L_PARTKEY || L_SUPPKEY AS PARTSUPPKEY --**
    ,N.N_NATIONKEY AS NATIONKEY
    ,R.R_REGIONKEY AS REGIONKEY
    ,O_ORDERDATE AS ORDERDATE
    ,YEAR(O_ORDERDATE) AS ORDERYEAR --**
    ,MONTH(O_ORDERDATE) AS ORDERMONTH --**
    ,MONTHNAME(O_ORDERDATE) AS ORDERMONTHNAME --**
    ,CASE WHEN MONTH(O_ORDERDATE) < 4 THEN 'Q1' ELSE
      CASE WHEN MONTH(O_ORDERDATE) < 7 THEN 'Q2' ELSE
        CASE WHEN MONTH(O_ORDERDATE) < 10 THEN 'Q3' ELSE 'Q4' END END END AS ORDERQUARTER --**
    ,O_TOTALPRICE AS TOTALPRICE
    ,L_LINENUMBER AS LINENUMBER
    ,L_QUANTITY AS QUANTITY
    ,L_EXTENDEDPRICE AS EXTENDEDPRICE 
    ,L_DISCOUNT AS DISCOUNT
    ,L_TAX AS TAX
    ,(L_EXTENDEDPRICE * L_DISCOUNT) AS DISCOUNTVALUE --**
    ,(L_EXTENDEDPRICE) - (L_EXTENDEDPRICE * L_DISCOUNT) AS NETPRICE --** 
    ,((L_EXTENDEDPRICE - (L_EXTENDEDPRICE * L_DISCOUNT))*L_TAX) AS TAXVALUE --**
    ,((L_EXTENDEDPRICE) - (L_EXTENDEDPRICE * L_DISCOUNT)) + ((L_EXTENDEDPRICE - (L_EXTENDEDPRICE * L_DISCOUNT))*L_TAX) AS SALEPRICE --**
FROM DW_SALES1.SALES1.ITEM1 join
     DW_SALES1.SALES1.SALES1 O ON (L_ORDERKEY = O.O_ORDERKEY) LEFT JOIN
     DW_SALES1.SALES1.CUSTOMER1 C ON (O.O_CUSTKEY = C.C_CUSTKEY) LEFT JOIN
     DW_SALES1.SALES1.NATION1 N ON (C.C_NATIONKEY = N.N_NATIONKEY) LEFT JOIN
     DW_SALES1.SALES1.REGION1 R ON (N.N_REGIONKEY = R.R_REGIONKEY);
     
USE WAREHOUSE XSMALL_WH;  

-- Faço um check na carga para comparar a tabela origem vs destino
SELECT
 'FULL_ORDES_ROW_COUNT' as step
 ,(SELECT ROW_COUNT FROM DW_SALES1.INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FACT_SALES1' ) as IMPORTADO
 ,(SELECT ROW_COUNT FROM SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TPCH_SF100' AND TABLE_NAME = 'LINEITEM' ) as expected

 ,'Check number of rows' as description;
