ALTER SESSION SET USE_CACHED_RESULT = FALSE;

USE WAREHOUSE SMALL_WH;

SELECT
    S.ORDERYEAR,
    N.N_NAME,
    R.R_NAME,
    SUM(TOTALPRICE) AS TOTALPRICE,
    SUM(DISCOUNTVALUE) AS DISCOUNTVALUE,
    SUM(NETPRICE) AS NETPRICE, 
    SUM(TAXVALUE) AS TAXVALUE,
    SUM(SALEPRICE) AS SALEPRICE
FROM DW_SALES1.SALES1.FACT_SALES1 S LEFT JOIN
     DW_SALES1.SALES1.CUSTOMER1 C ON (S.CUSTKEY = C_CUSTKEY) LEFT JOIN
     DW_SALES1.SALES1.NATION1 N ON (C.C_NATIONKEY = N.N_NATIONKEY) LEFT JOIN
     DW_SALES1.SALES1.REGION1 R ON (R.R_REGIONKEY = N.N_REGIONKEY)
GROUP BY 01,02, 03
ORDER BY 01;